version: '3.6'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    command: ["mongod", "--nojournal"]
    volumes:
      - '$MONGO_HOME:/data/db:z'
