version: '3.9'

services:
  gitlab-runner:
    deploy:
      resources:
        limits:
          cpus: '0.25'
    image: gitlab/gitlab-runner:alpine
    restart: unless-stopped
    volumes:
      - ./config/gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
