version: '3.8'

services:
  firebird:
    image: firebirdsql/firebird:latest
    environment:
      - FIREBIRD_ROOT_PASSWORD=masterkey
      - FIREBIRD_USER=test
      - FIREBIRD_PASSWORD=test
      - FIREBIRD_DATABASE=testdb.fdb
      - FIREBIRD_DATABASE_DEFAULT_CHARSET=UTF8
      - TZ=Europe/Berlin
    ports:
      - "3050:3050"
    volumes:
      - ${FIREBIRD_HOME:-./data/firebird}:/var/lib/firebird/data
    healthcheck:
      test: ["CMD", "isql", "-user", "SYSDBA", "-password", "masterkey", "localhost:testdb.fdb"]
      interval: 10s
      timeout: 5s
      retries: 5 